<script setup>
import {onMounted, ref} from "vue";

defineProps({
  options: {
    type: Array,
    default: [],
    validator: (options) => options.every(option => typeof option === 'object'),
  },
  name: String,
  label: String,
  id: String,
  required: {
    type: Boolean,
    default: false
  },
  modelValue: String
});

const inputRef = ref(null);
const isFocusedOrFilled = ref(false);

const updateFocusState = () => {
  isFocusedOrFilled.value = !!inputRef.value?.value;
};

const onFocus = () => {
  isFocusedOrFilled.value = true;
};

const onBlur = () => {
  if (!inputRef.value?.value) {
    updateFocusState();
  }
};

/**
 * A function that is called when the value of an input element changes.
 * If the input element has a value, it sets a boolean variable isFocusedOrFilled to true.
 *
 * @function
 * @name onChange
 * @memberof module
 * @returns {void}
 *
 * @example
 *
 * // Call the onChange function to handle the change event of an input element
 * onChange();
 */
const onChange = () => {
  if (inputRef.value?.value) {
    isFocusedOrFilled.value = true;
  }
}

const emits = defineEmits(['update:modelValue']);

/**
 * Updates the value of a model and emits an event.
 *
 * @param {Event} event - The event object generated by the user action.
 * @emits update:modelValue - The event emitted after updating the model value.
 */
const updateValue = (event) => {
  emits('update:modelValue', event.target.value); // emit event
}

onMounted(updateFocusState);
</script>

<template>
  <div class="w-full h-auto">
    <div class="flex relative flex-col justify-center h-11">
      <div class="flex relative">
        <label :for="id" @click="inputRef.focus()"
               :class="{'top-0 -translate-y-1 ml-2 text-xs auth-component-input-label-focused text-purple font-bold' : isFocusedOrFilled, 'top-[16px] ml-2.5 text-[15px] text-gray-500' : !isFocusedOrFilled }"
               class="block absolute px-1.5 py-0 font-normal leading-normal bg-white duration-300 ease-out cursor-text auth-component-input dark:text-gray-300">
          {{ label }}
          <span v-if="required" class="text-red-500">*</span>
        </label>

        <div data-model="email" class="mt-1.5 w-full rounded-md shadow-sm auth-component-input-container">
          <select
            :id="id"
            :name="name"
            :required="required"
            @focus="onFocus()"
            @blur="onBlur()"
            @change="onChange"
            :value="modelValue"
            @input="updateValue"
            ref="inputRef"
            class=" flex w-full h-11 px-3.5 text-sm bg-white border rounded-md border-gray-300 ring-offset-background placeholder:text-gray-500 focus:outline-none focus:border-0 focus:ring-2 focus:ring-purple disabled:cursor-not-allowed disabled:opacity-50"
          >
            <option value>---</option>
            <option v-for="option in options" :value="option.value" :key="option.value">{{ option.label }}</option>
          </select>
        </div>
      </div>
    </div>
    <slot></slot>
  </div>
</template>

<style scoped>

</style>
