version: '3.8'

services:
  app:
    build: .
    container_name: ispgo-app
    restart: unless-stopped
    ports:
      - "8191:80"
    environment:
      - APP_KEY=${APP_KEY}
      - APP_ENV=production
      - RUN_SETUP=true
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      # Quitamos el '.' y dejamos solo lo persistente
      - storage-data:/var/www/html/storage
      - cache-data:/var/www/html/bootstrap/cache
    networks:
      - ispgo-network
    depends_on:
      - redis
      - mysql

  worker:
    build: .
    container_name: ispgo-worker
    restart: unless-stopped
    environment:
      - APP_KEY=${APP_KEY}
      - RUN_SETUP=false
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - storage-data:/var/www/html/storage
      - cache-data:/var/www/html/bootstrap/cache
    networks:
      - ispgo-network
    depends_on:
      - app
    command: ["/usr/local/bin/run-worker.sh"]

  cron:
    build: .
    container_name: ispgo-cron
    restart: unless-stopped
    environment:
      - APP_KEY=${APP_KEY}
      - RUN_SETUP=false
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - storage-data:/var/www/html/storage
      - cache-data:/var/www/html/bootstrap/cache
    networks:
      - ispgo-network
    depends_on:
      - app
    command: ["/usr/local/bin/run-cron.sh"]

  mysql:
    image: mysql:8.0
    container_name: ispgo-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ispgo-network

  redis:
    image: redis:alpine
    container_name: ispgo-redis
    networks:
      - ispgo-network

networks:
  ispgo-network:
    driver: bridge

volumes:
  mysql-data:
  storage-data:
  cache-data:
