# nixpacks.toml

[phases.setup]
# La clave correcta es 'pkgs', no 'nixPkgs'.
pkgs = ["php83", "composer", "pnpm_8", "nginx"]

[start]
# Este comando de inicio sigue siendo correcto.
command = "nginx && php-fpm"
