[phases.setup]
nixPackages = ["php83", "composer"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --no-dev"]

[phases.build]
cmds = ["php artisan optimize"]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
