# nixpacks.toml

[phases.setup]
# Usamos Nix para casi todo
pkgs = ["php83", "pnpm", "nginx"]
# ¡PERO usamos Apt para instalar composer y evitar la colisión!
aptPkgs = ["composer"]

[start]
command = "nginx && php-fpm"
